### ISSUE TITLE
v.billhu.tk

### ISSUE THREAD

**Issue by billmatxas** [billmatxas/sss44#2]
由于众所周知的原因...最近停止v.billhubo.com的解析, 变为v.billhu.tk, sss.billhubo.com 一并转移为sss.billhu.tk
所以现在sss服务器地址为v.billhu.tk

**Comment by VincentXWD** [comment]
roger that

**Comment by VincentXWD** [comment]
roger that

**Comment by billmatxas** [comment]
习惯性close蛤😂

**Comment by VincentXWD** [comment]
yep

**Comment by Leo1971** [comment]
copy that.
