### ISSUE TITLE
green关闭

### ISSUE THREAD

**Issue by billmatxas** [billmatxas/sss44#3]
打击力度加大, green关闭, 如有使用他家服务记得8月31日前提交退款申请.
因此警示各位, 以后请不要在任何国内社交网络, 电话, 短信, 邮箱提及sss44和相关服务, 问题我也不会回复.
有问题, 直接来这开issue, 欢迎各位更换新的github小号😊
感谢各位支持...革命, 前路漫漫...

**Comment by VincentXWD** [comment]
R.I.P. GreenVPN
