### ISSUE TITLE
有人说不能用了

### ISSUE THREAD

**Issue by billmatxas** [billmatxas/sss44#6]
有人说不能用了，很可能是你的网络问题，要不就是你的配置问题，否则有疑问就发出

时间
所访问地址或应用名称
具体表现（比如错误代码或问题描述）
所处网络环境（联通/电信）
配置截图

反正越详细越好，要不然你说不能，我一试没问题，给你一张我的截图，问题也解决不了是不是

还有，最重要一点，国内的社交平台上面，包括电话短信，我都不可能回复的别天真了，直接提issue或者发邮件，你们放心肯定比QQ来的快。以后再这样连在这里回复都不可能了。

**Comment by lyzl** [comment]
这隐蔽工作做的很好啊..不过这有这么大必要么呃

**Comment by billmatxas** [comment]
你需要知道这并不是什么合法的事，只是还没有出台相关的处罚措施，你也看到最近一些事情，所以尽量低调吧。再说这里zf也不是不能看到的…
